package org.xdb.logging;

public enum EnumXDBComponents {
	CONFIG,
	COMPILE_CATALOG,
	COMPILE_CLIENT,
	COMPILE_SERVER,
	MASTER_TRACKER_CLIENT,
	MASTER_TRACKER_SERVER,
	QUERY_TRACKER_CLIENT,
	QUERY_TRACKER_SERVER,
	COMPUTE_CLIENT,
	COMPUTE_SERVER,
	PARTITIONER
}
