package org.xdb.funsql.statement;

public enum EnumStatement {
	CREATE_CONNECTION,
	DROP_CONNECTION,
	CREATE_SCHEMA,
	DROP_SCHEMA,
	CREATE_TABLE,
	DROP_TABLE,
	CREATE_FUNCTION,
	DROP_FUNCTION,
	CALL_FUNCTION,
	SELECT
}
