CREATE TABLE `ATTRIBUTE` (
    `OID` bigint NOT NULL,
    `NAME` character varying(255) NOT NULL,
    `TYPE` integer NOT NULL,
    `TABLE_OID` bigint NOT NULL
);

CREATE TABLE `CONNECTION` (
    `OID` bigint NOT NULL,
    `NAME` character varying(255) NOT NULL,
    `URL` character varying(1023) NOT NULL,
    `USER` character varying(255) NOT NULL,
    `PASSWD` character varying(255) NOT NULL,
    `STORE` integer NOT NULL
);


CREATE TABLE `FUNCTION` (
    `OID` bigint NOT NULL,
    `NAME` character varying(255) NOT NULL,
    `SCHEMA_OID` bigint NOT NULL,
    `LANGUAGE` bigint,
    `SOURCE` text
);


CREATE TABLE `SCHEMA` (
    `OID` bigint NOT NULL,
    `NAME` character varying(255) NOT NULL
);


CREATE TABLE `TABLE` (
    `OID` bigint NOT NULL,
    `NAME` character varying(255) NOT NULL,
    `SOURCE_NAME` character varying(255) NOT NULL,
    `SOURCE_SCHEMA` character varying(255) NOT NULL,
    `SCHEMA_OID` bigint NOT NULL,
    `CONNECTION_OID` bigint NOT NULL
);


INSERT INTO `SCHEMA` VALUES (1, 'PUBLIC');

ALTER TABLE `ATTRIBUTE`
    ADD CONSTRAINT `ATTRIBUTE_TABLE_OID_NAME_key` UNIQUE (`TABLE_OID`, `NAME`);

ALTER TABLE `ATTRIBUTE`
    ADD CONSTRAINT `ATTRIBUTE_pkey` PRIMARY KEY (`OID`);

ALTER TABLE `CONNECTION`
    ADD CONSTRAINT `CONNECTION_NAME_key` UNIQUE (`NAME`);

ALTER TABLE `CONNECTION`
    ADD CONSTRAINT `CONNECTION_pkey` PRIMARY KEY (`OID`);

ALTER TABLE `FUNCTION`
    ADD CONSTRAINT `FUNCTION_pkey` PRIMARY KEY (`OID`);

ALTER TABLE `SCHEMA`
    ADD CONSTRAINT `SCHEMA_NAME_key` UNIQUE (`NAME`);

ALTER TABLE `SCHEMA`
    ADD CONSTRAINT `SCHEMA_pkey` PRIMARY KEY (`OID`);

ALTER TABLE `TABLE`
    ADD CONSTRAINT `TABLE_SCHEMA_OID_NAME_key` UNIQUE (`SCHEMA_OID`, `NAME`);

ALTER TABLE `TABLE`
    ADD CONSTRAINT `TABLE_pkey` PRIMARY KEY (`OID`);

ALTER TABLE `ATTRIBUTE`
    ADD CONSTRAINT `ATTRIBUTE_TABLE_OID_fkey` FOREIGN KEY (`TABLE_OID`) REFERENCES `TABLE`(`OID`) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE `FUNCTION`
    ADD CONSTRAINT `FUNCTION_SCHEMA_OID_fkey` FOREIGN KEY (`SCHEMA_OID`) REFERENCES `SCHEMA`(`OID`) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE `TABLE`
    ADD CONSTRAINT `TABLE_CONNECTION_OID_fkey` FOREIGN KEY (`CONNECTION_OID`) REFERENCES `CONNECTION`(`OID`) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE `TABLE`
    ADD CONSTRAINT `TABLE_SCHEMA_OID_fkey` FOREIGN KEY (`SCHEMA_OID`) REFERENCES `SCHEMA`(`OID`) ON UPDATE RESTRICT ON DELETE RESTRICT;
